### ISSUE TITLE
BetterRoleColors voice color option is broken now

### ISSUE THREAD

**Issue by Mef45** [rauenzi/BetterDiscordAddons#13]
This error appear in console only if "Voice" option is enabled and there is someone in the voice with colored nickname.
Ubuntu GNOME 17.04, BD v0.2.81:792
`Uncaught TypeError: Cannot read property 'style' of null
    at document.querySelectorAll.forEach (<anonymous>:319:41)
    at Plugin.colorizeVoice (<anonymous>:315:53)
    at Plugin.observer (<anonymous>:161:15)
    at Object.<anonymous> (https://cdn.rawgit.com/Jiiks/BetterDiscordApp/1d074365695cae0024cc94e6db9000dffddce51b/js/main.min.js:131:1066)
    at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js:4:4626)
    at PluginModule.rawObserver (https://cdn.rawgit.com/Jiiks/BetterDiscordApp/1d074365695cae0024cc94e6db9000dffddce51b/js/main.min.js:131:936)
    at https://cdn.rawgit.com/Jiiks/BetterDiscordApp/1d074365695cae0024cc94e6db9000dffddce51b/js/main.min.js:9:51
    at Array.forEach (native)
    at MutationObserver.<anonymous> (https://cdn.rawgit.com/Jiiks/BetterDiscordApp/1d074365695cae0024cc94e6db9000dffddce51b/js/main.min.js:7:716)`

**Comment by rauenzi** [comment]
This should be fixed with the latest update, let me know if the error still occurs.
