### ISSUE TITLE
[Bug] DoNotTrack does not seem to work anymore

### ISSUE THREAD

**Issue by rojnwa** [rauenzi/BetterDiscordAddons#202]
**Which plugin/theme is this about?**
DoNotTrack - Version 0.0.5

**Describe the Bug**
Discord still displays the current game above the username and mute/deafen button.

**To Reproduce**
Open up a game which is detectable by discord.

**Expected Behavior**
Discord should not be able to detect the current game, hence not display the game.

**Screenshots**
https://i.vgy.me/zk2YWE.png

**Discord Version**
Stable 53724 (e714ac3)
Host 0.0.305
Windows 10 64-Bit (10.0.18362)

**Additional Context**
Using:
ZeresPluginLibrary v1.2.9 by Zerebos
DoNotTrack v0.0.5 by Zerebos
HideDisabledEmojis v0.0.6 by Zerebos
BadgesEverywhere v1.5.1 by DevilBro

**Comment by rekkisomo** [comment]
This shows in console as well.
```
Uncaught (in promise) TypeError: Reporter.report.uninstall is not a function
    at DoNotTrack.onStart (C:\Users\sledd\AppData\Roaming\BetterDiscord\plugins\DoNotTrack.plugin.js:75)
    at DoNotTrack.start (VM437 C:\Users\sledd\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:6301)
    at PluginModule.startPlugin (main.min.js:55)
    at PluginModule.enablePlugin (main.min.js:55)
    at PluginModule.togglePlugin (main.min.js:55)
    at V2C_PluginCard.onChange (main.min.js:55)
    at Object.E (731ab33d9a027b17f668.js:73)
    at I (731ab33d9a027b17f668.js:73)
    at 731ab33d9a027b17f668.js:73
    at O (731ab33d9a027b17f668.js:73)
    at L (731ab33d9a027b17f668.js:73)
    at Array.forEach (<anonymous>)
    at N (731ab33d9a027b17f668.js:73)
    at D (731ab33d9a027b17f668.js:73)
    at On (731ab33d9a027b17f668.js:73)
    at ce (731ab33d9a027b17f668.js:73)
    at Cn (731ab33d9a027b17f668.js:73)
    at Mn (731ab33d9a027b17f668.js:73)
    at Pn (731ab33d9a027b17f668.js:73)
    at t.unstable_runWithPriority (731ab33d9a027b17f668.js:81)
    at Ji (731ab33d9a027b17f668.js:73)
    at bu (731ab33d9a027b17f668.js:73)
    at Ln (731ab33d9a027b17f668.js:73)
    at HTMLDocument.r (b639fea0c24acb7814b7.js:16)
```

**Comment by rojnwa** [comment]
For me it's also three errors in console.

```
Uncaught (in promise) TypeError: Reporter.report.uninstall is not a function
    at DoNotTrack.onStart (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\DoNotTrack.plugin.js:75:29)
    at DoNotTrack.start (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:6301:58)
    at PluginModule.loadPlugins (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:23554)
    at Core.init (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:4:683)
```

```
Uncaught (in promise) TypeError: Reporter.report.uninstall is not a function
    at DoNotTrack.onStart (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\DoNotTrack.plugin.js:75:29)
    at DoNotTrack.start (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:6301:58)
    at PluginModule.startPlugin (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:24084)
    at PluginModule.reloadPlugin (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:27488)
    at PluginLibrary.load (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:3921:71)
    at PluginModule.reloadPlugin (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:27473)
    at FSWatcher.watchers.(anonymous function).t.watch (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:19100)
```

```
Uncaught (in promise) TypeError: Reporter.report.uninstall is not a function
    at DoNotTrack.onStart (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\DoNotTrack.plugin.js:75:29)
    at DoNotTrack.start (C:\Users\Neonardo\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:6301:58)
    at PluginModule.startPlugin (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:24084)
    at PluginModule.reloadPlugin (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:27488)
    at FSWatcher.watchers.(anonymous function).t.watch (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/c07e8f38de2a2df4cd37cd48201a7e6038287b5b/js/main.min.js:55:19100)
```

**Comment by rauenzi** [comment]
Yes I am trying to find the new way to kill Sentry

**Comment by rojnwa** [comment]
Commit did not fix the problem. Updated - restarted Discord and quit/relaunched game. Still showing game status.

Following lines are coming up upon launching a game (League of Legends in this case).

![Discord_2020-02-10_00-14-52](https://user-images.githubusercontent.com/19150352/74112139-62a13400-4b9a-11ea-981f-39b4d764ea34.png)

**Comment by rauenzi** [comment]
Did you actually enable the setting in DNT for that? I cannot reproduce the issue where the game is detected. The "playing game" above status should be stuck, that is true.

**Comment by rojnwa** [comment]
Yea I have that enabled. To be sure I just disabled it and enabled it again. Including restarts and so on. Still not working.

**Comment by rojnwa** [comment]
So why is this issue closed? Apparently I still have this error and can't solve it. Reinstalled everything - still not solved.

**Comment by rauenzi** [comment]
Because I, nor several users that I asked to check were able to recreate the part of _new_ processes showing in console under the `[RunningGameStore]` tag. They were however able to recreate #186 which sounds like the original description here:
> Discord still displays the current game above the username and mute/deafen button.

**Comment by nullKomplex** [comment]
It doesn't work for me either. What information can I provide to assist?
