### ISSUE TITLE
[Bug] BlurNSFW

### ISSUE THREAD

**Issue by alsoGAMER** [rauenzi/BetterDiscordAddons#287]
**Which plugin/theme is this about?**
BlurNSFW

**Describe the Bug**
```
[EnhancedDiscord] [BlurNSFW] Failed to load:
ReferenceError: ModalActions is not defined
    at Function.showConfirmationModal (/home/USER/Documents/EnhancedDiscord/dom_shit.js:291:9)
    at module.exports.global.ZeresPluginLibrary.plugin.Patcher.Patcher.load (/home/USER/Documents/EnhancedDiscord/plugins/BlurNSFW.plugin.js:43:19)
    at Plugin.load (/home/USER/Documents/EnhancedDiscord/bd_shit.js:134:29)
    at loadPlugin (/home/USER/Documents/EnhancedDiscord/dom_shit.js:87:16)
    at process.<anonymous> (/home/USER/Documents/EnhancedDiscord/dom_shit.js:197:9)
(anonymous) @ 202cf4cccacc9609a8bc.js:16
```

**To Reproduce**
Start Discord with EnhancedDiscord injected and BlurNSFW enabled

**Expected Behavior**
The plugin would load normally.

**Discord Version**
Stable 0.0.12

**Comment by alsoGAMER** [comment]
Fixed by installing [this](https://rauenzi.github.io/BDPluginLibrary/release/0PluginLibrary.plugin.js), that for an unknown reason any of your plugin hasn't prompted me to download
