### ISSUE TITLE
[Bug] [BetterRoleColors] Not showing role color in profile modal

### ISSUE THREAD

**Issue by rauenzi** [rauenzi/BetterDiscordAddons#454]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by XxUnkn0wnxX** [comment]
+ audit log
I get this error in debug log

```
[2021-08-18 17:10:00.277][CONSOLE:ERROR] [Suppression] Error occurred in mentions patch {} Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at BetterRoleColors.patchMentions (betterdiscord://plugins/BetterRoleColors.plugin.js:183:41)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:3373:25
    at BetterRoleColors.onStart (betterdiscord://plugins/BetterRoleColors.plugin.js:108:86)
    at BetterRoleColors.start (betterdiscord://plugins/0PluginLibrary.plugin.js:6466:58)
    at Object.startPlugin (<anonymous>:4:231836)
    at Object.startAddon (<anonymous>:4:231631)
    at Object.loadAddon (<anonymous>:4:192820)
    at Object.loadAddon (<anonymous>:4:229804)
    at Object.loadAllAddons (<anonymous>:4:194920)
    at Object.initialize (<anonymous>:4:189410)
    at Object.initialize (<anonymous>:4:229014)
    at Object.startup (<anonymous>:4:291165)
```

**Comment by rauenzi** [comment]
This has been fixed at the latest version.
