### ISSUE TITLE
[Bug] channelpermissions crashes discord when changing channels sometimes (as of latest update?)

### ISSUE THREAD

**Issue by tntmod54321** [rauenzi/BetterDiscordAddons#633]
[2022-08-03 08:47:31.721][CONSOLE:LOG] [Routing/Utils] transitionTo - Transitioning to /channels/{id}/{id}
[2022-08-03 08:47:35.219][CONSOLE:ERROR] channel.isVocal is not a function
TypeError: channel.isVocal is not a function
    at useActiveThreads (betterdiscord://plugins/ChannelPermissions.plugin.js:213:16)
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelPermissions.plugin.js:242:5)
    at so (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6008:468)
    at $s (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6060:48)
    at Gu (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6051:748)
    at wu (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6051:676)
    at Uu (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6051:539)
    at Au (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6048:164)
    at https://discord.com/assets/2afa166ab2e5ff2f7e19.js:5993:340
    at t.unstable_runWithPriority (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6182:828)
    at Ki (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:5993:117)
    at qi (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:5993:285)
    at Xi (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:5993:220)
    at Tu (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6045:510)
    at Object.enqueueSetState (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:5997:240)
    at t.h.setState (https://discord.com/assets/2afa166ab2e5ff2f7e19.js:6152:297)
    at betterdiscord://plugins/ChannelPermissions.plugin.js:325:18
    at r (https://discord.com/assets/75c2c0189d2f4bde01cb.js:126:559)

**Comment by lyratcm** [comment]
im seeing it even when not doing anything after a few mins
b2b24985a6279e26878c.js:130 TypeError: channel.isVocal is not a function
    at useActiveThreads (ChannelPermissions.plugin.js:213)
    at PatchedThreadsPopout (ChannelPermissions.plugin.js:242)
    at so (0edf27b372d69e9e5bf0.js:6011)
    at $s (0edf27b372d69e9e5bf0.js:6063)
    at Gu (0edf27b372d69e9e5bf0.js:6054)
    at wu (0edf27b372d69e9e5bf0.js:6054)
    at Uu (0edf27b372d69e9e5bf0.js:6054)
    at Au (0edf27b372d69e9e5bf0.js:6051)
    at 0edf27b372d69e9e5bf0.js:5996
    at t.unstable_runWithPriority (0edf27b372d69e9e5bf0.js:6185)
    at Ki (0edf27b372d69e9e5bf0.js:5996)
    at qi (0edf27b372d69e9e5bf0.js:5996)
    at Xi (0edf27b372d69e9e5bf0.js:5996)
    at Tu (0edf27b372d69e9e5bf0.js:6048)
    at Object.enqueueSetState (0edf27b372d69e9e5bf0.js:6000)
    at t.h.setState (0edf27b372d69e9e5bf0.js:6155)
    at ChannelPermissions.plugin.js:325
    at r (b2b24985a6279e26878c.js:126)

**Comment by acendvgnt** [comment]
1. ChannelPermissions plugin is not from this repo. It's from [this one](https://github.com/Farcrada/DiscordPlugins/tree/master/Channel-Permissions).
2. There's a [fix](https://github.com/Farcrada/DiscordPlugins/pull/102). It just hasn't been updated yet.
3. If you want to have the fix now, you can do it by simply replacing "isVocal()" with "isGuildVocal()".

**Comment by Farcrada** [comment]
Apologies for the delay. Should be merged now in: https://github.com/Farcrada/DiscordPlugins/commit/0001230fffcc92e61a8b710081b7e3f3fa9a2926
