### ISSUE TITLE
[Bug] blurNSFW and probably other couldn't load

### ISSUE THREAD

**Issue by orblazer** [rauenzi/BetterDiscordAddons#657]
**Which plugin/theme is this about?**

blurNSFW

**Describe the Bug**

The plugin couldn't load

Log:
```
TypeError: Cannot read property 'default' of undefined
    at plugin (betterdiscord://plugins/BlurNSFW.plugin.js:126:77)
    at eval (betterdiscord://plugins/BlurNSFW.plugin.js:277:13)
    at eval (betterdiscord://plugins/BlurNSFW.plugin.js:278:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)
```

**To Reproduce**

Add the last version of plugin with BetterDiscord 1.7.0

**Expected Behavior**

Work.

**Screenshots**

**Discord Version**

Stable

**Additional Context**

This is due to https://github.com/BetterDiscord/BetterDiscord/issues/1404

**Comment by sixy69** [comment]
any update?

**Comment by ccrowles** [comment]
For probably the same reason, BetterFormattingRedux doesn't work. It shows the buttons, but they do nothing.

**Comment by rauenzi** [comment]
Should be fixed with latest update.
