### ISSUE TITLE
Plugin could not be compiled (BetterRoleColors 0.9.1)[Bug] 

### ISSUE THREAD

**Issue by BialySztorm** [rauenzi/BetterDiscordAddons#671]
**Which plugin/theme is this about?**

BetterRoleColors 0.9.1

**Describe the Bug**

The plugin did't load

**To Reproduce**

I'm installed the newest version of BetterRoleColors

**Expected Behavior**

**Screenshots**

`TypeError: Cannot read property 'name' of undefined
    at Function.buildPlugin (betterdiscord://plugins/0PluginLibrary.plugin.js:3430:38)
    at eval (betterdiscord://plugins/BetterRoleColors.plugin.js:495:30)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)`

**Discord Version**

Stable 152727

**Additional Context**

**Comment by rauenzi** [comment]
This is fixed
